### ISSUE TITLE
Rubric assessment

### ISSUE THREAD

**Issue by ReiniervanLimpt** [StefanGerrits2/real-time-web-1920#1]
1. Project: Project is online, we spoke about possible variants of questions you could ask in the quiz, instead of only having questions about the temperature you could also include humidity or multiple choise questions. Data lifecycle is very clear and ledgible, maybe you could think about what happens when someone gave a wrong answer to a question??
2. Complexity: Your app requires rooms to be made and sockets will be assigned certain roles based on the state of the game, nice!
3. client-server interaction: Users can create questions by requesting weather data from a specific city, to check this criteria it would be cool if the question picker can choose what kind of question (multiple choise, open question) they want to ask.
4. data management: Server keeps track of which socket connection answered the most questions correctly, it also saves the current weather conditions of cities which have been the topic of a question.
5. Multi-user Support: The game can be played with any number of users, doesnt require a full room to run properly (i think), very clean.

**Comment by StefanGerrits2** [comment]
Thanks for your feedback,

1. I implemented multiple choice questions about the current temperature.
2. The application has 1 room, but each round the roles do indeed change based on if they have already been the question picker, I also handle errors, dynamically calculate points and keep track of the scores.
3. Check! I implemented multiple choice. You can also still choose for an open question.
4. Check
5. You're right. I also support that a user can join mid game, and play along
