### ISSUE TITLE
Data Lifecycle Diagram

### ISSUE THREAD

**Issue by ReiniervanLimpt** [StefanGerrits2/real-time-web-1920#2]
Data stripped from the API's data object get stored to be used when another user asks a question about the same city, you might want to expand on the data you keep to make questions more interesting.

very clear flow and events between client and server.

The update-points feels like a function you could handle within the server.js, you could instead emit something like a answer-result event which gives feedback on wether the answer was wrong or correct.

**Comment by StefanGerrits2** [comment]
Thanks for the feedback,

I did not expand on the data since you can't really guess a city's humidy or the current clouds etc,
I did implement multiple choice questions though.

When you guess the answer you get feedback that you guessed it.
